# -*- coding: utf-8 -*-
"""Best_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUxt8a0fvqjV4AS5Umg1Y29cp0UJKyOa
"""

import streamlit as st
import numpy as np
import joblib

# Cargar el modelo entrenado (XGBoost)
best_model = joblib.load("best_model.pkl")

# Umbral óptimo definido
THRESHOLD = 0.6207  # Cambia si usaste otro threshold óptimo

# Título de la app
st.title("🔍 Detección de Fraude en Tarjetas de Crédito")
st.write("Ingrese los valores de una transacción (PCA) para evaluar si es potencialmente fraudulenta.")

# Crear formulario de entrada con 30 features (PCA transformados)
input_values = []
for i in range(30):
    value = st.number_input(f"PC{i+1}", step=0.01, format="%.4f")
    input_values.append(value)

# Botón de predicción
if st.button("📊 Evaluar transacción"):
    input_array = np.array(input_values).reshape(1, -1)
    prob = best_model.predict_proba(input_array)[0][1]

    st.write(f"📈 Probabilidad de fraude: **{prob:.4f}**")

    if prob >= THRESHOLD:
        st.error("⚠️ ¡Fraude detectado!")
    else:
        st.success("✅ Transacción normal")